version: '2'
services:
  mysql:
    image: mariadb:10.3
    container_name: mariadb
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql/votings.sql:/docker-entrypoint-initdb.d/votings.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: votings
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"

  grafana:
    image: grafana/grafana
    user: "1000"
    ports:
      - '3001:3000'
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel

  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /tmp/metabase.db
    volumes:
      - ./metabase:/tmp



